version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - echo Pre-Build started on `date`
      - gradle wrapper
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
    on-failure: ABORT
    finally:
      - echo Build success
  post_build:
    commands:
      - echo Build completed on `date`
    finally:
      - rm -f  /root/.gradle/caches/modules-2/modules-2.lock
      - rm -fr /root/.gradle/caches/*/plugin-resolution/
artifacts:
  files:
    - '*-all.jar'
  base-directory: 'build/libs'
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
